2020-02-21 21:07:39,809 - [test_register.py-->line:53] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-21 21:07:39,958 - [test_register.py-->line:53] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-21 21:07:40,031 - [test_register.py-->line:53] - INFO: 用例：不输入手机号，执行未通过
2020-02-21 21:07:40,113 - [test_register.py-->line:53] - INFO: 用例：手机号长度10位，执行未通过
2020-02-21 21:07:40,190 - [test_register.py-->line:53] - INFO: 用例：手机号长度12位，执行未通过
2020-02-21 21:07:40,275 - [test_register.py-->line:53] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-21 21:07:40,418 - [test_register.py-->line:53] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-21 21:07:40,491 - [test_register.py-->line:53] - INFO: 用例：密码7位，执行未通过
2020-02-21 21:07:40,580 - [test_register.py-->line:53] - INFO: 用例：密码17位，执行未通过
2020-02-21 21:07:40,663 - [test_register.py-->line:53] - INFO: 用例：不输入密码，执行未通过
2020-02-21 21:07:40,749 - [test_register.py-->line:53] - INFO: 用例：注册名11位，执行未通过
2020-02-21 21:07:40,848 - [test_register.py-->line:53] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-21 21:07:40,989 - [test_register.py-->line:53] - INFO: 用例：不输入类型，执行未通过
2020-02-21 21:23:53,689 - [test_register.py-->line:88] - INFO: 用例：登录成功，执行未通过
2020-02-21 21:23:53,791 - [test_register.py-->line:83] - ERROR: 用例：手机号为空，执行未通过
2020-02-21 21:23:53,792 - [test_register.py-->line:84] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 79, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-21 21:23:53,868 - [test_register.py-->line:83] - ERROR: 用例：密码为空，执行未通过
2020-02-21 21:23:53,870 - [test_register.py-->line:84] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 79, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-21 21:23:53,951 - [test_register.py-->line:88] - INFO: 用例：手机号未注册，执行未通过
2020-02-21 21:23:54,031 - [test_register.py-->line:88] - INFO: 用例：密码错误，执行未通过
2020-02-21 21:23:54,140 - [test_register.py-->line:88] - INFO: 用例：手机号格式错误，执行未通过
2020-02-21 21:23:54,230 - [test_register.py-->line:48] - ERROR: 用例：注册成功-带注册名，执行未通过
2020-02-21 21:23:54,230 - [test_register.py-->line:49] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 44, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-21 21:23:54,292 - [test_register.py-->line:48] - ERROR: 用例：成功-不带用户名，执行未通过
2020-02-21 21:23:54,293 - [test_register.py-->line:49] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 44, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-21 21:23:54,385 - [test_register.py-->line:53] - INFO: 用例：不输入手机号，执行未通过
2020-02-21 21:23:54,455 - [test_register.py-->line:53] - INFO: 用例：手机号长度10位，执行未通过
2020-02-21 21:23:54,520 - [test_register.py-->line:53] - INFO: 用例：手机号长度12位，执行未通过
2020-02-21 21:23:54,588 - [test_register.py-->line:53] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-21 21:23:54,660 - [test_register.py-->line:53] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-21 21:23:54,749 - [test_register.py-->line:53] - INFO: 用例：密码7位，执行未通过
2020-02-21 21:23:54,818 - [test_register.py-->line:53] - INFO: 用例：密码17位，执行未通过
2020-02-21 21:23:54,906 - [test_register.py-->line:53] - INFO: 用例：不输入密码，执行未通过
2020-02-21 21:23:54,979 - [test_register.py-->line:53] - INFO: 用例：注册名11位，执行未通过
2020-02-21 21:23:55,053 - [test_register.py-->line:53] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-21 21:23:55,125 - [test_register.py-->line:48] - ERROR: 用例：不输入类型，执行未通过
2020-02-21 21:23:55,125 - [test_register.py-->line:49] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 44, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-21 21:28:26,062 - [test_register.py-->line:88] - INFO: 用例：登录成功，执行未通过
2020-02-21 21:28:26,176 - [test_register.py-->line:83] - ERROR: 用例：手机号为空，执行未通过
2020-02-21 21:28:26,177 - [test_register.py-->line:84] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 79, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-21 21:28:26,296 - [test_register.py-->line:83] - ERROR: 用例：密码为空，执行未通过
2020-02-21 21:28:26,296 - [test_register.py-->line:84] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 79, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-21 21:28:26,496 - [test_register.py-->line:88] - INFO: 用例：手机号未注册，执行未通过
2020-02-21 21:28:26,757 - [test_register.py-->line:88] - INFO: 用例：密码错误，执行未通过
2020-02-21 21:28:26,930 - [test_register.py-->line:88] - INFO: 用例：手机号格式错误，执行未通过
2020-02-21 21:28:27,170 - [test_register.py-->line:48] - ERROR: 用例：注册成功-带注册名，执行未通过
2020-02-21 21:28:27,172 - [test_register.py-->line:49] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 44, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-21 21:28:27,335 - [test_register.py-->line:48] - ERROR: 用例：成功-不带用户名，执行未通过
2020-02-21 21:28:27,337 - [test_register.py-->line:49] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 44, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-21 21:28:27,490 - [test_register.py-->line:53] - INFO: 用例：不输入手机号，执行未通过
2020-02-21 21:28:27,627 - [test_register.py-->line:53] - INFO: 用例：手机号长度10位，执行未通过
2020-02-21 21:28:27,730 - [test_register.py-->line:53] - INFO: 用例：手机号长度12位，执行未通过
2020-02-21 21:28:27,844 - [test_register.py-->line:53] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-21 21:28:28,034 - [test_register.py-->line:53] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-21 21:28:28,146 - [test_register.py-->line:53] - INFO: 用例：密码7位，执行未通过
2020-02-21 21:28:28,247 - [test_register.py-->line:53] - INFO: 用例：密码17位，执行未通过
2020-02-21 21:28:28,362 - [test_register.py-->line:53] - INFO: 用例：不输入密码，执行未通过
2020-02-21 21:28:28,467 - [test_register.py-->line:53] - INFO: 用例：注册名11位，执行未通过
2020-02-21 21:28:28,612 - [test_register.py-->line:53] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-21 21:28:28,795 - [test_register.py-->line:48] - ERROR: 用例：不输入类型，执行未通过
2020-02-21 21:28:28,795 - [test_register.py-->line:49] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 44, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-21 21:45:13,820 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-21 21:45:13,919 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-21 21:45:13,919 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-21 21:45:14,016 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-21 21:45:14,016 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-21 21:45:14,189 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-21 21:45:14,354 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-21 21:45:14,460 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-21 21:45:14,661 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-21 21:45:14,829 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-21 21:45:14,937 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-21 21:45:15,073 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-21 21:45:15,171 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-21 21:45:15,283 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-21 21:45:15,445 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-21 21:45:15,586 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-21 21:45:15,687 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-21 21:45:15,790 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-21 21:45:15,895 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-21 21:45:16,036 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-21 21:45:16,211 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 11:55:42,820 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 11:55:42,970 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号未注册，执行未通过
2020-02-24 11:55:43,052 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号格式错误，执行未通过
2020-02-24 11:55:43,137 - [test_register.py-->line:91] - ERROR: 用例：登录失败-手机号为空，执行未通过
2020-02-24 11:55:43,137 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:55:43,332 - [test_register.py-->line:96] - INFO: 用例：登录失败-密码错误，执行未通过
2020-02-24 11:55:43,412 - [test_register.py-->line:91] - ERROR: 用例：登录失败-密码为空，执行未通过
2020-02-24 11:55:43,413 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:55:43,581 - [test_register.py-->line:57] - INFO: 用例：注册失败-重复注册，执行未通过
2020-02-24 11:55:43,660 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号为空，执行未通过
2020-02-24 11:55:43,734 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码为12位，执行未通过
2020-02-24 11:55:43,809 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码不全为数字，执行未通过
2020-02-24 11:55:43,887 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码为空，执行未通过
2020-02-24 11:55:43,968 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于7位，执行未通过
2020-02-24 11:55:44,054 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于17位，执行未通过
2020-02-24 11:58:16,134 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 11:58:16,295 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号未注册，执行未通过
2020-02-24 11:58:16,371 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号格式错误，执行未通过
2020-02-24 11:58:16,448 - [test_register.py-->line:91] - ERROR: 用例：登录失败-手机号为空，执行未通过
2020-02-24 11:58:16,448 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:58:16,599 - [test_register.py-->line:96] - INFO: 用例：登录失败-密码错误，执行未通过
2020-02-24 11:58:16,677 - [test_register.py-->line:91] - ERROR: 用例：登录失败-密码为空，执行未通过
2020-02-24 11:58:16,677 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:58:16,842 - [test_register.py-->line:57] - INFO: 用例：注册失败-重复注册，执行未通过
2020-02-24 11:58:16,922 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号为空，执行未通过
2020-02-24 11:58:17,017 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码为12位，执行未通过
2020-02-24 11:58:17,097 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码不全为数字，执行未通过
2020-02-24 11:58:17,175 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码为空，执行未通过
2020-02-24 11:58:17,256 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于7位，执行未通过
2020-02-24 11:58:17,332 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于17位，执行未通过
2020-02-24 11:59:02,880 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 11:59:03,038 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号未注册，执行未通过
2020-02-24 11:59:03,109 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号格式错误，执行未通过
2020-02-24 11:59:03,198 - [test_register.py-->line:91] - ERROR: 用例：登录失败-手机号为空，执行未通过
2020-02-24 11:59:03,198 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:59:03,338 - [test_register.py-->line:96] - INFO: 用例：登录失败-密码错误，执行未通过
2020-02-24 11:59:03,411 - [test_register.py-->line:91] - ERROR: 用例：登录失败-密码为空，执行未通过
2020-02-24 11:59:03,411 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:59:03,596 - [test_register.py-->line:57] - INFO: 用例：注册失败-重复注册，执行未通过
2020-02-24 11:59:03,698 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号为空，执行未通过
2020-02-24 11:59:03,791 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码为12位，执行未通过
2020-02-24 11:59:03,876 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码不全为数字，执行未通过
2020-02-24 11:59:03,957 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码为空，执行未通过
2020-02-24 11:59:04,033 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于7位，执行未通过
2020-02-24 11:59:04,117 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于17位，执行未通过
2020-02-24 11:59:30,897 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 11:59:31,035 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号未注册，执行未通过
2020-02-24 11:59:31,112 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号格式错误，执行未通过
2020-02-24 11:59:31,187 - [test_register.py-->line:91] - ERROR: 用例：登录失败-手机号为空，执行未通过
2020-02-24 11:59:31,187 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:59:31,335 - [test_register.py-->line:96] - INFO: 用例：登录失败-密码错误，执行未通过
2020-02-24 11:59:31,424 - [test_register.py-->line:91] - ERROR: 用例：登录失败-密码为空，执行未通过
2020-02-24 11:59:31,424 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 11:59:31,590 - [test_register.py-->line:57] - INFO: 用例：注册失败-重复注册，执行未通过
2020-02-24 11:59:31,686 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号为空，执行未通过
2020-02-24 11:59:31,765 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码为12位，执行未通过
2020-02-24 11:59:31,844 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码不全为数字，执行未通过
2020-02-24 11:59:31,925 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码为空，执行未通过
2020-02-24 11:59:32,003 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于7位，执行未通过
2020-02-24 11:59:32,078 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于17位，执行未通过
2020-02-24 12:00:16,909 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 12:00:16,982 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号未注册，执行未通过
2020-02-24 12:00:17,053 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号格式错误，执行未通过
2020-02-24 12:00:17,123 - [test_register.py-->line:91] - ERROR: 用例：登录失败-手机号为空，执行未通过
2020-02-24 12:00:17,123 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 12:00:17,196 - [test_register.py-->line:96] - INFO: 用例：登录失败-密码错误，执行未通过
2020-02-24 12:00:17,266 - [test_register.py-->line:91] - ERROR: 用例：登录失败-密码为空，执行未通过
2020-02-24 12:00:17,266 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 12:00:17,379 - [test_register.py-->line:57] - INFO: 用例：注册失败-重复注册，执行未通过
2020-02-24 12:00:17,483 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号为空，执行未通过
2020-02-24 12:00:17,588 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码为12位，执行未通过
2020-02-24 12:00:17,690 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码不全为数字，执行未通过
2020-02-24 12:00:17,769 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码为空，执行未通过
2020-02-24 12:00:17,852 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于7位，执行未通过
2020-02-24 12:00:17,948 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于17位，执行未通过
2020-02-24 15:09:22,597 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 15:09:22,733 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号未注册，执行未通过
2020-02-24 15:09:22,811 - [test_register.py-->line:96] - INFO: 用例：登录失败-手机号格式错误，执行未通过
2020-02-24 15:09:22,885 - [test_register.py-->line:91] - ERROR: 用例：登录失败-手机号为空，执行未通过
2020-02-24 15:09:22,885 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 15:09:23,043 - [test_register.py-->line:96] - INFO: 用例：登录失败-密码错误，执行未通过
2020-02-24 15:09:23,114 - [test_register.py-->line:91] - ERROR: 用例：登录失败-密码为空，执行未通过
2020-02-24 15:09:23,114 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 15:09:23,284 - [test_register.py-->line:57] - INFO: 用例：注册失败-重复注册，执行未通过
2020-02-24 15:09:23,386 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号为空，执行未通过
2020-02-24 15:09:23,474 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码为12位，执行未通过
2020-02-24 15:09:23,553 - [test_register.py-->line:57] - INFO: 用例：注册失败-手机号码不全为数字，执行未通过
2020-02-24 15:09:23,628 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码为空，执行未通过
2020-02-24 15:09:23,718 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于7位，执行未通过
2020-02-24 15:09:23,804 - [test_register.py-->line:57] - INFO: 用例：注册失败-密码等于17位，执行未通过
2020-02-24 15:10:00,894 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 15:10:00,982 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 15:10:00,982 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 15:10:01,070 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 15:10:01,071 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 15:10:01,217 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 15:10:01,360 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 15:10:01,448 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 15:10:01,605 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 15:10:01,736 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 15:10:01,811 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 15:10:01,886 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 15:10:01,961 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 15:10:02,048 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 15:10:02,189 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 15:10:02,269 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 15:10:02,343 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 15:10:02,419 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 15:10:02,517 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 15:10:02,591 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 15:10:02,758 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 20:24:45,602 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 20:24:45,980 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 20:24:45,980 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 20:24:46,378 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 20:24:46,379 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 20:24:46,803 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 20:24:47,194 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 20:24:47,552 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 20:24:48,063 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 20:24:48,489 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 20:24:48,621 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 20:24:48,792 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 20:24:48,946 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 20:24:49,104 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 20:24:49,321 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 20:24:49,491 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 20:24:49,687 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 20:24:49,830 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 20:24:49,973 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 20:24:50,116 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 20:24:50,349 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 20:27:45,653 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 20:27:45,789 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 20:27:45,789 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 20:27:45,986 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 20:27:45,986 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 20:27:46,231 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 20:27:46,434 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 20:27:46,589 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 20:27:46,858 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 20:27:47,088 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 20:27:47,230 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 20:27:47,362 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 20:27:47,533 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 20:27:47,715 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 20:27:47,929 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 20:27:48,056 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 20:27:48,178 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 20:27:48,304 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 20:27:48,455 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 20:27:48,584 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 20:27:48,800 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 20:28:38,663 - [test_rechage.py-->line:78] - INFO: 用例：充值成功-整数，执行未通过
2020-02-24 20:28:38,826 - [test_rechage.py-->line:78] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-24 20:28:38,964 - [test_rechage.py-->line:78] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-24 20:28:39,158 - [test_rechage.py-->line:78] - INFO: 用例：充值成功-50万，执行未通过
2020-02-24 20:28:39,285 - [test_rechage.py-->line:78] - INFO: 用例：会员id为空，执行未通过
2020-02-24 20:28:39,412 - [test_rechage.py-->line:78] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-24 20:28:39,558 - [test_rechage.py-->line:73] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-24 20:28:39,558 - [test_rechage.py-->line:74] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 69, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 20:28:39,700 - [test_rechage.py-->line:78] - INFO: 用例：会员id为小数，执行未通过
2020-02-24 20:28:39,852 - [test_rechage.py-->line:73] - ERROR: 用例：充值金额为0，执行未通过
2020-02-24 20:28:39,852 - [test_rechage.py-->line:74] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 69, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 20:28:40,050 - [test_rechage.py-->line:78] - INFO: 用例：充值金额为负数，执行未通过
2020-02-24 20:28:40,193 - [test_rechage.py-->line:73] - ERROR: 用例：充值金额为空，执行未通过
2020-02-24 20:28:40,193 - [test_rechage.py-->line:74] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 69, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 20:28:40,387 - [test_rechage.py-->line:78] - INFO: 用例：充值金额-3位小数，执行未通过
2020-02-24 20:28:40,525 - [test_rechage.py-->line:78] - INFO: 用例：充值金额-大于50万，执行未通过
2020-02-24 20:28:40,683 - [test_rechage.py-->line:78] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-24 20:28:40,917 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 20:28:41,068 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 20:28:41,068 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 20:28:41,266 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 20:28:41,266 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 20:28:41,459 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 20:28:41,682 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 20:28:41,861 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 20:28:42,101 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 20:28:42,294 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 20:28:42,430 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 20:28:42,579 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 20:28:42,745 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 20:28:42,881 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 20:28:43,092 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 20:28:43,225 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 20:28:43,391 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 20:28:43,515 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 20:28:43,654 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 20:28:43,780 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 20:28:43,988 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 21:51:57,500 - [test_rechage.py-->line:91] - ERROR: 用例：充值成功-整数，执行未通过
2020-02-24 21:51:57,500 - [test_rechage.py-->line:92] - ERROR: Decimal('0.00') != 600
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 88, in test_recharge
    self.assertEqual(end_money - start_money, data["amount"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('0.00') != 600
2020-02-24 21:51:57,852 - [test_rechage.py-->line:91] - ERROR: 用例：充值成功-1位小数，执行未通过
2020-02-24 21:51:57,852 - [test_rechage.py-->line:92] - ERROR: Decimal('0.00') != 600.1
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 88, in test_recharge
    self.assertEqual(end_money - start_money, data["amount"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('0.00') != 600.1
2020-02-24 21:51:58,295 - [test_rechage.py-->line:91] - ERROR: 用例：充值成功-2位小数，执行未通过
2020-02-24 21:51:58,295 - [test_rechage.py-->line:92] - ERROR: Decimal('0.00') != 600.22
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 88, in test_recharge
    self.assertEqual(end_money - start_money, data["amount"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('0.00') != 600.22
2020-02-24 21:51:58,661 - [test_rechage.py-->line:91] - ERROR: 用例：充值成功-50万，执行未通过
2020-02-24 21:51:58,661 - [test_rechage.py-->line:92] - ERROR: Decimal('0.00') != 500000
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 88, in test_recharge
    self.assertEqual(end_money - start_money, data["amount"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('0.00') != 500000
2020-02-24 21:51:58,847 - [test_rechage.py-->line:96] - INFO: 用例：会员id为空，执行未通过
2020-02-24 21:51:59,059 - [test_rechage.py-->line:96] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-24 21:51:59,246 - [test_rechage.py-->line:91] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-24 21:51:59,246 - [test_rechage.py-->line:92] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 21:51:59,448 - [test_rechage.py-->line:96] - INFO: 用例：会员id为小数，执行未通过
2020-02-24 21:51:59,611 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额为0，执行未通过
2020-02-24 21:51:59,612 - [test_rechage.py-->line:92] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 21:51:59,835 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-24 21:51:59,835 - [test_rechage.py-->line:92] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 21:52:00,136 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额为空，执行未通过
2020-02-24 21:52:00,136 - [test_rechage.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 21:52:00,356 - [test_rechage.py-->line:96] - INFO: 用例：充值金额-3位小数，执行未通过
2020-02-24 21:52:00,558 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-24 21:52:00,558 - [test_rechage.py-->line:92] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 21:52:00,728 - [test_rechage.py-->line:96] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-24 21:52:01,009 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 21:52:01,170 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 21:52:01,171 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 21:52:01,379 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 21:52:01,379 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 21:52:01,626 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 21:52:01,868 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 21:52:02,053 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 21:52:02,354 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 21:52:02,614 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 21:52:02,785 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 21:52:02,969 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 21:52:03,130 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 21:52:03,310 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 21:52:03,555 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 21:52:03,745 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 21:52:03,926 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 21:52:04,110 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 21:52:04,292 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 21:52:04,466 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 21:52:04,718 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 21:59:43,662 - [test_rechage.py-->line:96] - INFO: 用例：充值成功-整数，执行未通过
2020-02-24 21:59:43,993 - [test_rechage.py-->line:91] - ERROR: 用例：充值成功-1位小数，执行未通过
2020-02-24 21:59:43,993 - [test_rechage.py-->line:92] - ERROR: Decimal('600.10') != 600.1
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 88, in test_recharge
    self.assertEqual(end_money - start_money, data["amount"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('600.10') != 600.1
2020-02-24 21:59:44,381 - [test_rechage.py-->line:91] - ERROR: 用例：充值成功-2位小数，执行未通过
2020-02-24 21:59:44,381 - [test_rechage.py-->line:92] - ERROR: Decimal('600.22') != 600.22
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 88, in test_recharge
    self.assertEqual(end_money - start_money, data["amount"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('600.22') != 600.22
2020-02-24 21:59:44,745 - [test_rechage.py-->line:96] - INFO: 用例：充值成功-50万，执行未通过
2020-02-24 21:59:44,868 - [test_rechage.py-->line:96] - INFO: 用例：会员id为空，执行未通过
2020-02-24 21:59:44,998 - [test_rechage.py-->line:96] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-24 21:59:45,146 - [test_rechage.py-->line:91] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-24 21:59:45,147 - [test_rechage.py-->line:92] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 21:59:45,290 - [test_rechage.py-->line:96] - INFO: 用例：会员id为小数，执行未通过
2020-02-24 21:59:45,427 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额为0，执行未通过
2020-02-24 21:59:45,428 - [test_rechage.py-->line:92] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 21:59:45,582 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-24 21:59:45,582 - [test_rechage.py-->line:92] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 21:59:45,731 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额为空，执行未通过
2020-02-24 21:59:45,732 - [test_rechage.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 21:59:45,862 - [test_rechage.py-->line:96] - INFO: 用例：充值金额-3位小数，执行未通过
2020-02-24 21:59:45,995 - [test_rechage.py-->line:91] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-24 21:59:45,996 - [test_rechage.py-->line:92] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 21:59:46,145 - [test_rechage.py-->line:96] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-24 21:59:46,353 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 21:59:46,479 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 21:59:46,479 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 21:59:46,666 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 21:59:46,666 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 21:59:46,857 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 21:59:47,055 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 21:59:47,184 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 21:59:47,419 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 21:59:47,611 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 21:59:47,766 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 21:59:47,898 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 21:59:48,049 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 21:59:48,180 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 21:59:48,388 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 21:59:48,519 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 21:59:48,679 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 21:59:48,811 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 21:59:49,014 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 21:59:49,167 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 21:59:49,375 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 22:03:36,732 - [test_rechage.py-->line:97] - INFO: 用例：充值成功-整数，执行未通过
2020-02-24 22:03:37,040 - [test_rechage.py-->line:97] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-24 22:03:37,376 - [test_rechage.py-->line:97] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-24 22:03:37,704 - [test_rechage.py-->line:97] - INFO: 用例：充值成功-50万，执行未通过
2020-02-24 22:03:37,852 - [test_rechage.py-->line:97] - INFO: 用例：会员id为空，执行未通过
2020-02-24 22:03:37,981 - [test_rechage.py-->line:97] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-24 22:03:38,113 - [test_rechage.py-->line:92] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-24 22:03:38,114 - [test_rechage.py-->line:93] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 22:03:38,263 - [test_rechage.py-->line:97] - INFO: 用例：会员id为小数，执行未通过
2020-02-24 22:03:38,402 - [test_rechage.py-->line:92] - ERROR: 用例：充值金额为0，执行未通过
2020-02-24 22:03:38,402 - [test_rechage.py-->line:93] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 22:03:38,591 - [test_rechage.py-->line:92] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-24 22:03:38,591 - [test_rechage.py-->line:93] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 86, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 22:03:38,736 - [test_rechage.py-->line:92] - ERROR: 用例：充值金额为空，执行未通过
2020-02-24 22:03:38,736 - [test_rechage.py-->line:93] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 22:03:38,914 - [test_rechage.py-->line:97] - INFO: 用例：充值金额-3位小数，执行未通过
2020-02-24 22:03:39,054 - [test_rechage.py-->line:92] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-24 22:03:39,054 - [test_rechage.py-->line:93] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 86, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 22:03:39,204 - [test_rechage.py-->line:97] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-24 22:03:39,427 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 22:03:39,547 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 22:03:39,547 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 22:03:39,693 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 22:03:39,693 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 22:03:39,883 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 22:03:40,096 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 22:03:40,213 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 22:03:40,434 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 22:03:40,635 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 22:03:40,771 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 22:03:40,900 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 22:03:41,023 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 22:03:41,160 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 22:03:41,354 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 22:03:41,490 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 22:03:41,660 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 22:03:41,813 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 22:03:41,990 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 22:03:42,123 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 22:03:42,332 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-24 22:06:00,593 - [test_rechage.py-->line:99] - INFO: 用例：充值成功-整数，执行未通过
2020-02-24 22:06:00,934 - [test_rechage.py-->line:99] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-24 22:06:01,315 - [test_rechage.py-->line:99] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-24 22:06:01,677 - [test_rechage.py-->line:99] - INFO: 用例：充值成功-50万，执行未通过
2020-02-24 22:06:01,806 - [test_rechage.py-->line:99] - INFO: 用例：会员id为空，执行未通过
2020-02-24 22:06:01,960 - [test_rechage.py-->line:99] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-24 22:06:02,123 - [test_rechage.py-->line:94] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-24 22:06:02,123 - [test_rechage.py-->line:95] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 22:06:02,270 - [test_rechage.py-->line:99] - INFO: 用例：会员id为小数，执行未通过
2020-02-24 22:06:02,406 - [test_rechage.py-->line:94] - ERROR: 用例：充值金额为0，执行未通过
2020-02-24 22:06:02,406 - [test_rechage.py-->line:95] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-24 22:06:02,565 - [test_rechage.py-->line:94] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-24 22:06:02,565 - [test_rechage.py-->line:95] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 86, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 22:06:02,770 - [test_rechage.py-->line:94] - ERROR: 用例：充值金额为空，执行未通过
2020-02-24 22:06:02,770 - [test_rechage.py-->line:95] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 22:06:02,961 - [test_rechage.py-->line:99] - INFO: 用例：充值金额-3位小数，执行未通过
2020-02-24 22:06:03,096 - [test_rechage.py-->line:94] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-24 22:06:03,096 - [test_rechage.py-->line:95] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 86, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-24 22:06:03,285 - [test_rechage.py-->line:99] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-24 22:06:03,526 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-24 22:06:03,655 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-24 22:06:03,655 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 22:06:03,820 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-24 22:06:03,821 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-24 22:06:04,083 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-24 22:06:04,311 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-24 22:06:04,458 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-24 22:06:04,698 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-24 22:06:04,956 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-24 22:06:05,156 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-24 22:06:05,357 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-24 22:06:05,544 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-24 22:06:05,691 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-24 22:06:05,906 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-24 22:06:06,067 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-24 22:06:06,238 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-24 22:06:06,407 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-24 22:06:06,579 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-24 22:06:06,744 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-24 22:06:06,976 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-26 10:09:24,602 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 10:09:24,864 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 10:09:25,150 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 10:09:25,401 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 10:09:25,491 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 10:09:25,574 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 10:09:25,685 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 10:09:25,686 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 10:09:25,774 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 10:09:25,879 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 10:09:25,879 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 10:09:25,966 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 10:09:25,966 - [test_rechage.py-->line:94] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 10:09:26,063 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 10:09:26,063 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 10:09:26,155 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-3位小数，执行未通过
2020-02-26 10:09:26,240 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 10:09:26,240 - [test_rechage.py-->line:94] - ERROR: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '充值金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 充值金额必须大于0并且小于或者等于500000
? ^^^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 10:09:26,321 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 10:09:26,491 - [test_register.py-->line:96] - INFO: 用例：登录成功，执行未通过
2020-02-26 10:09:26,565 - [test_register.py-->line:91] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 10:09:26,565 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 10:09:26,648 - [test_register.py-->line:91] - ERROR: 用例：密码为空，执行未通过
2020-02-26 10:09:26,649 - [test_register.py-->line:92] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 87, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 10:09:26,797 - [test_register.py-->line:96] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 10:09:26,947 - [test_register.py-->line:96] - INFO: 用例：密码错误，执行未通过
2020-02-26 10:09:27,023 - [test_register.py-->line:96] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 10:09:27,212 - [test_register.py-->line:57] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 10:09:27,378 - [test_register.py-->line:57] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 10:09:27,461 - [test_register.py-->line:57] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 10:09:27,543 - [test_register.py-->line:57] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 10:09:27,634 - [test_register.py-->line:57] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 10:09:27,717 - [test_register.py-->line:57] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 10:09:27,864 - [test_register.py-->line:57] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 10:09:27,946 - [test_register.py-->line:57] - INFO: 用例：密码7位，执行未通过
2020-02-26 10:09:28,034 - [test_register.py-->line:57] - INFO: 用例：密码17位，执行未通过
2020-02-26 10:09:28,117 - [test_register.py-->line:57] - INFO: 用例：不输入密码，执行未通过
2020-02-26 10:09:28,200 - [test_register.py-->line:57] - INFO: 用例：注册名11位，执行未通过
2020-02-26 10:09:28,281 - [test_register.py-->line:57] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 10:09:28,435 - [test_register.py-->line:57] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:11:23,874 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:11:24,179 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:11:24,501 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:11:24,794 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:11:24,920 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:11:25,043 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:11:25,183 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:11:25,183 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:11:25,362 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:11:25,497 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:11:25,498 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:11:25,643 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:11:25,643 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:11:25,787 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:11:25,787 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:11:25,954 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:11:25,954 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:11:26,102 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:11:26,102 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:11:26,298 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:11:26,552 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:11:26,685 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:11:26,685 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:11:26,875 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:11:26,875 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:11:27,103 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:11:27,324 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:11:27,473 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:11:27,832 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:11:28,151 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:11:28,306 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:11:28,472 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:11:28,608 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:11:28,730 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:11:28,938 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:11:29,064 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:11:29,185 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:11:29,354 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:11:29,501 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:11:29,626 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:11:29,937 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:36:31,974 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:36:32,515 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:36:33,035 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:36:33,553 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:36:33,876 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:36:33,999 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:36:34,143 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:36:34,143 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:36:34,288 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:36:34,471 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:36:34,471 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:36:34,599 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:36:34,599 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:36:34,732 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:36:34,732 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:36:34,863 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:36:34,863 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:36:34,998 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:36:34,998 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:36:35,129 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:36:35,375 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:36:35,541 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:36:35,541 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:36:35,701 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:36:35,701 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:36:35,921 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:36:36,120 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:36:36,263 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:36:36,658 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:36:37,019 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:36:37,141 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:36:37,290 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:36:37,420 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:36:37,557 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:36:37,766 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:36:37,895 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:36:38,033 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:36:38,164 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:36:38,333 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:36:38,461 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:36:38,792 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:39:54,720 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:39:55,093 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:39:55,433 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:39:55,770 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:39:55,897 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:39:56,042 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:39:56,176 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:39:56,176 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:39:56,356 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:39:56,508 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:39:56,508 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:39:56,724 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:39:56,724 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:39:56,872 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:39:56,873 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:39:57,047 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:39:57,049 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:39:57,216 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:39:57,217 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:39:57,381 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:39:57,626 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:39:57,751 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:39:57,751 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:39:57,875 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:39:57,876 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:39:58,075 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:39:58,281 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:39:58,409 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:39:58,972 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:39:59,288 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:39:59,419 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:39:59,554 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:39:59,675 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:39:59,817 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:40:00,026 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:40:00,155 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:40:00,297 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:40:00,430 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:40:00,560 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:40:00,691 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:40:01,032 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:40:01,270 - [test_wothdraw.py-->line:73] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:41:08,101 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:41:08,420 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:41:08,709 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:41:09,253 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:41:09,388 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:41:09,553 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:41:09,743 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:41:09,743 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:41:09,910 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:41:10,042 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:41:10,042 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:41:10,191 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:41:10,191 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:41:10,353 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:41:10,354 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:41:10,522 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:41:10,523 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:41:10,657 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:41:10,658 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:41:10,859 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:41:11,083 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:41:11,211 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:41:11,211 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:41:11,353 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:41:11,354 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:41:11,547 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:41:11,741 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:41:11,856 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:41:12,225 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:41:12,551 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:41:12,670 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:41:12,792 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:41:12,920 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:41:13,056 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:41:13,258 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:41:13,388 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:41:13,516 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:41:13,637 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:41:13,763 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:41:13,898 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:41:14,230 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:41:14,526 - [test_wothdraw.py-->line:73] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:41:14,660 - [test_wothdraw.py-->line:73] - INFO: 用例：提现成功-整数，执行未通过
2020-02-26 20:41:14,798 - [test_wothdraw.py-->line:73] - INFO: 用例：提现成功-1位小数，执行未通过
2020-02-26 20:41:14,936 - [test_wothdraw.py-->line:73] - INFO: 用例：提现成功-2位小数，执行未通过
2020-02-26 20:41:15,078 - [test_wothdraw.py-->line:73] - INFO: 用例：提现成功-50万，执行未通过
2020-02-26 20:41:15,196 - [test_wothdraw.py-->line:73] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:41:15,321 - [test_wothdraw.py-->line:73] - INFO: 用例：会员id不存在，执行未通过
2020-02-26 20:41:15,455 - [test_wothdraw.py-->line:68] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:41:15,456 - [test_wothdraw.py-->line:69] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 62, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:41:15,606 - [test_wothdraw.py-->line:73] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:41:15,753 - [test_wothdraw.py-->line:68] - ERROR: 用例：提现金额为0，执行未通过
2020-02-26 20:41:15,753 - [test_wothdraw.py-->line:69] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 62, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:41:15,918 - [test_wothdraw.py-->line:68] - ERROR: 用例：提现金额为负数，执行未通过
2020-02-26 20:41:15,918 - [test_wothdraw.py-->line:69] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:41:16,061 - [test_wothdraw.py-->line:68] - ERROR: 用例：提现金额为空，执行未通过
2020-02-26 20:41:16,061 - [test_wothdraw.py-->line:69] - ERROR: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^

2020-02-26 20:41:16,254 - [test_wothdraw.py-->line:68] - ERROR: 用例：提现金额-3位小数，执行未通过
2020-02-26 20:41:16,254 - [test_wothdraw.py-->line:69] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:41:16,404 - [test_wothdraw.py-->line:68] - ERROR: 用例：提现金额-大于50万，执行未通过
2020-02-26 20:41:16,405 - [test_wothdraw.py-->line:69] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:41:16,554 - [test_wothdraw.py-->line:73] - INFO: 用例：提现金额-非数字，执行未通过
2020-02-26 20:51:31,320 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:51:31,673 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:51:32,016 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:51:32,335 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:51:32,464 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:51:32,596 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:51:32,733 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:51:32,733 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:51:32,887 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:51:33,033 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:51:33,033 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:51:33,234 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:51:33,234 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:51:33,362 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:51:33,362 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:51:33,528 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:51:33,528 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:51:33,663 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:51:33,663 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:51:33,810 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:51:33,997 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:51:34,145 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:51:34,145 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:51:34,276 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:51:34,276 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:51:34,508 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:51:34,706 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:51:34,843 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:51:35,197 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:51:35,529 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:51:35,646 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:51:35,774 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:51:35,907 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:51:36,040 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:51:36,240 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:51:36,376 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:51:36,509 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:51:36,642 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:51:36,775 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:51:36,908 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:51:37,229 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:51:37,476 - [test_wothdraw.py-->line:80] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:51:37,660 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:51:37,811 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id不存在，执行未通过
2020-02-26 20:51:37,950 - [test_wothdraw.py-->line:75] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:51:37,951 - [test_wothdraw.py-->line:76] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:51:38,109 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:51:38,240 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为0，执行未通过
2020-02-26 20:51:38,240 - [test_wothdraw.py-->line:76] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:51:38,398 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为负数，执行未通过
2020-02-26 20:51:38,398 - [test_wothdraw.py-->line:76] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:51:38,532 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为空，执行未通过
2020-02-26 20:51:38,532 - [test_wothdraw.py-->line:76] - ERROR: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^

2020-02-26 20:51:38,678 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额-3位小数，执行未通过
2020-02-26 20:51:38,678 - [test_wothdraw.py-->line:76] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:51:38,819 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额-大于50万，执行未通过
2020-02-26 20:51:38,819 - [test_wothdraw.py-->line:76] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:51:39,010 - [test_wothdraw.py-->line:80] - INFO: 用例：提现金额-非数字，执行未通过
2020-02-26 20:53:51,865 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:53:52,270 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:53:52,644 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:53:53,040 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:53:53,200 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:53:53,355 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:53:53,522 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:53:53,523 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:53:53,687 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:53:53,838 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:53:53,838 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:53:54,007 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:53:54,007 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:53:54,157 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:53:54,157 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:53:54,325 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:53:54,325 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:53:54,554 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:53:54,557 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:53:54,751 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:53:54,995 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:53:55,144 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:53:55,144 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:53:55,282 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:53:55,283 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:53:55,484 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:53:55,694 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:53:55,865 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:53:56,276 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:53:56,623 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:53:56,776 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:53:56,921 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:53:57,078 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:53:57,222 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:53:57,423 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:53:57,558 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:53:57,691 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:53:57,823 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:53:57,991 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:53:58,113 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:53:58,471 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:53:58,730 - [test_wothdraw.py-->line:80] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:53:58,963 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:53:59,102 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id不存在，执行未通过
2020-02-26 20:53:59,236 - [test_wothdraw.py-->line:75] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:53:59,236 - [test_wothdraw.py-->line:76] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:53:59,368 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:53:59,497 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为0，执行未通过
2020-02-26 20:53:59,497 - [test_wothdraw.py-->line:76] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:53:59,619 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为负数，执行未通过
2020-02-26 20:53:59,620 - [test_wothdraw.py-->line:76] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:53:59,794 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为空，执行未通过
2020-02-26 20:53:59,794 - [test_wothdraw.py-->line:76] - ERROR: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^

2020-02-26 20:53:59,960 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额-3位小数，执行未通过
2020-02-26 20:53:59,961 - [test_wothdraw.py-->line:76] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:54:00,130 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额-大于50万，执行未通过
2020-02-26 20:54:00,130 - [test_wothdraw.py-->line:76] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:54:00,287 - [test_wothdraw.py-->line:80] - INFO: 用例：提现金额-非数字，执行未通过
2020-02-26 20:54:14,818 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:54:15,147 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:54:15,492 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:54:15,822 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:54:15,960 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:54:16,096 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:54:16,247 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:54:16,248 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:54:16,405 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:54:16,571 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:54:16,572 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:54:16,751 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:54:16,752 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:54:16,907 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:54:16,907 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:54:17,072 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:54:17,072 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:54:17,229 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:54:17,230 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:54:17,390 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:54:17,618 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:54:17,764 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:54:17,764 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:54:17,925 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:54:17,925 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:54:18,112 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:54:18,311 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:54:18,433 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:54:18,798 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:54:19,122 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:54:19,301 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:54:19,488 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:54:19,678 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:54:19,838 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:54:20,037 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:54:20,191 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:54:20,341 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:54:20,476 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:54:20,625 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:54:20,807 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:54:21,143 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:54:21,503 - [test_wothdraw.py-->line:80] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:54:22,587 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:54:22,719 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id不存在，执行未通过
2020-02-26 20:54:22,853 - [test_wothdraw.py-->line:75] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:54:22,853 - [test_wothdraw.py-->line:76] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:54:23,002 - [test_wothdraw.py-->line:80] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:54:23,143 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为0，执行未通过
2020-02-26 20:54:23,144 - [test_wothdraw.py-->line:76] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:54:23,296 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为负数，执行未通过
2020-02-26 20:54:23,296 - [test_wothdraw.py-->line:76] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:54:23,429 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额为空，执行未通过
2020-02-26 20:54:23,430 - [test_wothdraw.py-->line:76] - ERROR: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^

2020-02-26 20:54:23,568 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额-3位小数，执行未通过
2020-02-26 20:54:23,568 - [test_wothdraw.py-->line:76] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:54:23,705 - [test_wothdraw.py-->line:75] - ERROR: 用例：提现金额-大于50万，执行未通过
2020-02-26 20:54:23,705 - [test_wothdraw.py-->line:76] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:54:23,844 - [test_wothdraw.py-->line:80] - INFO: 用例：提现金额-非数字，执行未通过
2020-02-26 20:56:36,338 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-整数，执行未通过
2020-02-26 20:56:36,691 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-26 20:56:37,035 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-26 20:56:37,370 - [test_rechage.py-->line:98] - INFO: 用例：充值成功-50万，执行未通过
2020-02-26 20:56:37,494 - [test_rechage.py-->line:98] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:56:37,628 - [test_rechage.py-->line:98] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-26 20:56:37,764 - [test_rechage.py-->line:93] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:56:37,764 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:56:37,901 - [test_rechage.py-->line:98] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:56:38,051 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为0，执行未通过
2020-02-26 20:56:38,052 - [test_rechage.py-->line:94] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:56:38,199 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-26 20:56:38,200 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:56:38,337 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额为空，执行未通过
2020-02-26 20:56:38,338 - [test_rechage.py-->line:94] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 84, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:56:38,520 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-26 20:56:38,520 - [test_rechage.py-->line:94] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:56:38,661 - [test_rechage.py-->line:93] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-26 20:56:38,661 - [test_rechage.py-->line:94] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 85, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-26 20:56:38,824 - [test_rechage.py-->line:98] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-26 20:56:39,076 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:56:39,235 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-26 20:56:39,235 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:56:39,387 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-26 20:56:39,387 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-26 20:56:39,567 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-26 20:56:39,773 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-26 20:56:39,898 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-26 20:56:40,254 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-26 20:56:40,573 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-26 20:56:40,705 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-26 20:56:40,839 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-26 20:56:40,962 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-26 20:56:41,115 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-26 20:56:41,317 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-26 20:56:41,473 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-26 20:56:41,603 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-26 20:56:41,754 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-26 20:56:41,894 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-26 20:56:42,025 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-26 20:56:42,393 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-26 20:56:42,644 - [test_wothdraw.py-->line:79] - INFO: 用例：登录成功，执行未通过
2020-02-26 20:56:43,063 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-整数，执行未通过
2020-02-26 20:56:43,402 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-1位小数，执行未通过
2020-02-26 20:56:43,740 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-2位小数，执行未通过
2020-02-26 20:56:44,078 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-50万，执行未通过
2020-02-26 20:56:44,207 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id为空，执行未通过
2020-02-26 20:56:44,338 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id不存在，执行未通过
2020-02-26 20:56:44,481 - [test_wothdraw.py-->line:74] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-26 20:56:44,482 - [test_wothdraw.py-->line:75] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:56:44,631 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id为小数，执行未通过
2020-02-26 20:56:44,780 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为0，执行未通过
2020-02-26 20:56:44,781 - [test_wothdraw.py-->line:75] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-26 20:56:44,957 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为负数，执行未通过
2020-02-26 20:56:44,957 - [test_wothdraw.py-->line:75] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:56:45,101 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为空，执行未通过
2020-02-26 20:56:45,101 - [test_wothdraw.py-->line:75] - ERROR: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^

2020-02-26 20:56:45,263 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额-3位小数，执行未通过
2020-02-26 20:56:45,263 - [test_wothdraw.py-->line:75] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-26 20:56:45,386 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额-大于50万，执行未通过
2020-02-26 20:56:45,387 - [test_wothdraw.py-->line:75] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-26 20:56:45,569 - [test_wothdraw.py-->line:79] - INFO: 用例：提现金额-非数字，执行未通过
2020-02-28 20:58:04,522 - [test_rechage.py-->line:100] - INFO: 用例：会员id为空，执行未通过
2020-02-28 20:58:04,866 - [test_rechage.py-->line:100] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-28 20:58:05,348 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-28 20:58:05,701 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-28 20:58:05,701 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-28 20:58:05,870 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-28 20:58:05,870 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-28 20:58:06,107 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-28 20:58:06,333 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-28 20:58:06,480 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-28 20:58:06,868 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-28 20:58:07,218 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-28 20:58:07,367 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-28 20:58:07,511 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-28 20:58:07,669 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-28 20:58:07,833 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-28 20:58:08,084 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-28 20:58:08,219 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-28 20:58:08,365 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-28 20:58:08,514 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-28 20:58:08,681 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-28 20:58:08,841 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-28 20:58:09,169 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-28 20:58:09,634 - [test_wothdraw.py-->line:79] - INFO: 用例：登录成功，执行未通过
2020-02-28 20:58:10,219 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-整数，执行未通过
2020-02-28 20:58:10,832 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-1位小数，执行未通过
2020-02-28 20:58:11,207 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-2位小数，执行未通过
2020-02-28 20:58:11,580 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-50万，执行未通过
2020-02-28 20:58:11,735 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id为空，执行未通过
2020-02-28 20:58:11,961 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id不存在，执行未通过
2020-02-28 20:58:12,134 - [test_wothdraw.py-->line:74] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-28 20:58:12,134 - [test_wothdraw.py-->line:75] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-28 20:58:12,314 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id为小数，执行未通过
2020-02-28 20:58:12,465 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为0，执行未通过
2020-02-28 20:58:12,465 - [test_wothdraw.py-->line:75] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-28 20:58:12,636 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为负数，执行未通过
2020-02-28 20:58:12,636 - [test_wothdraw.py-->line:75] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-28 20:58:12,810 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为空，执行未通过
2020-02-28 20:58:12,811 - [test_wothdraw.py-->line:75] - ERROR: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^

2020-02-28 20:58:12,982 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额-3位小数，执行未通过
2020-02-28 20:58:12,982 - [test_wothdraw.py-->line:75] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-28 20:58:13,130 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额-大于50万，执行未通过
2020-02-28 20:58:13,130 - [test_wothdraw.py-->line:75] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-28 20:58:13,301 - [test_wothdraw.py-->line:79] - INFO: 用例：提现金额-非数字，执行未通过
2020-02-28 20:59:47,794 - [test_rechage.py-->line:100] - INFO: 用例：充值成功-整数，执行未通过
2020-02-28 20:59:48,152 - [test_rechage.py-->line:100] - INFO: 用例：充值成功-1位小数，执行未通过
2020-02-28 20:59:48,508 - [test_rechage.py-->line:100] - INFO: 用例：充值成功-2位小数，执行未通过
2020-02-28 20:59:48,879 - [test_rechage.py-->line:100] - INFO: 用例：充值成功-50万，执行未通过
2020-02-28 20:59:49,027 - [test_rechage.py-->line:100] - INFO: 用例：会员id为空，执行未通过
2020-02-28 20:59:49,179 - [test_rechage.py-->line:100] - INFO: 用例：id不是当前登录的用户，执行未通过
2020-02-28 20:59:49,344 - [test_rechage.py-->line:95] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-28 20:59:49,344 - [test_rechage.py-->line:96] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 86, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-28 20:59:49,546 - [test_rechage.py-->line:100] - INFO: 用例：会员id为小数，执行未通过
2020-02-28 20:59:49,742 - [test_rechage.py-->line:95] - ERROR: 用例：充值金额为0，执行未通过
2020-02-28 20:59:49,742 - [test_rechage.py-->line:96] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 86, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-28 20:59:49,936 - [test_rechage.py-->line:95] - ERROR: 用例：充值金额为负数，执行未通过
2020-02-28 20:59:49,937 - [test_rechage.py-->line:96] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 87, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-28 20:59:50,087 - [test_rechage.py-->line:95] - ERROR: 用例：充值金额为空，执行未通过
2020-02-28 20:59:50,087 - [test_rechage.py-->line:96] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 86, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-28 20:59:50,282 - [test_rechage.py-->line:95] - ERROR: 用例：充值金额-3位小数，执行未通过
2020-02-28 20:59:50,282 - [test_rechage.py-->line:96] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 87, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-28 20:59:50,440 - [test_rechage.py-->line:95] - ERROR: 用例：充值金额-大于50万，执行未通过
2020-02-28 20:59:50,441 - [test_rechage.py-->line:96] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_rechage.py", line 87, in test_recharge
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于500000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于500000
? ^

2020-02-28 20:59:50,647 - [test_rechage.py-->line:100] - INFO: 用例：充值金额-非数字，执行未通过
2020-02-28 20:59:50,906 - [test_register.py-->line:102] - INFO: 用例：登录成功，执行未通过
2020-02-28 20:59:51,047 - [test_register.py-->line:97] - ERROR: 用例：手机号为空，执行未通过
2020-02-28 20:59:51,047 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-28 20:59:51,235 - [test_register.py-->line:97] - ERROR: 用例：密码为空，执行未通过
2020-02-28 20:59:51,235 - [test_register.py-->line:98] - ERROR: 1 != 2
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_register.py", line 93, in test_login
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-28 20:59:51,452 - [test_register.py-->line:102] - INFO: 用例：手机号未注册，执行未通过
2020-02-28 20:59:51,684 - [test_register.py-->line:102] - INFO: 用例：密码错误，执行未通过
2020-02-28 20:59:51,840 - [test_register.py-->line:102] - INFO: 用例：手机号格式错误，执行未通过
2020-02-28 20:59:52,222 - [test_register.py-->line:63] - INFO: 用例：注册成功-带注册名，执行未通过
2020-02-28 20:59:52,573 - [test_register.py-->line:63] - INFO: 用例：成功-不带用户名，执行未通过
2020-02-28 20:59:52,742 - [test_register.py-->line:63] - INFO: 用例：不输入手机号，执行未通过
2020-02-28 20:59:52,916 - [test_register.py-->line:63] - INFO: 用例：手机号长度10位，执行未通过
2020-02-28 20:59:53,075 - [test_register.py-->line:63] - INFO: 用例：手机号长度12位，执行未通过
2020-02-28 20:59:53,250 - [test_register.py-->line:63] - INFO: 用例：手机号含有非法字符，执行未通过
2020-02-28 20:59:53,414 - [test_register.py-->line:63] - INFO: 用例：已注册过的手机号，执行未通过
2020-02-28 20:59:53,628 - [test_register.py-->line:63] - INFO: 用例：密码7位，执行未通过
2020-02-28 20:59:53,781 - [test_register.py-->line:63] - INFO: 用例：密码17位，执行未通过
2020-02-28 20:59:53,948 - [test_register.py-->line:63] - INFO: 用例：不输入密码，执行未通过
2020-02-28 20:59:54,104 - [test_register.py-->line:63] - INFO: 用例：注册名11位，执行未通过
2020-02-28 20:59:54,265 - [test_register.py-->line:63] - INFO: 用例：类型输入非0，1内容，执行未通过
2020-02-28 20:59:54,614 - [test_register.py-->line:63] - INFO: 用例：不输入类型，执行未通过
2020-02-28 20:59:54,882 - [test_wothdraw.py-->line:79] - INFO: 用例：登录成功，执行未通过
2020-02-28 20:59:55,210 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-整数，执行未通过
2020-02-28 20:59:55,539 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-1位小数，执行未通过
2020-02-28 20:59:55,873 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-2位小数，执行未通过
2020-02-28 20:59:56,197 - [test_wothdraw.py-->line:79] - INFO: 用例：提现成功-50万，执行未通过
2020-02-28 20:59:56,344 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id为空，执行未通过
2020-02-28 20:59:56,507 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id不存在，执行未通过
2020-02-28 20:59:56,670 - [test_wothdraw.py-->line:74] - ERROR: 用例：会员id为字符串，执行未通过
2020-02-28 20:59:56,670 - [test_wothdraw.py-->line:75] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-28 20:59:56,841 - [test_wothdraw.py-->line:79] - INFO: 用例：会员id为小数，执行未通过
2020-02-28 20:59:56,987 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为0，执行未通过
2020-02-28 20:59:56,987 - [test_wothdraw.py-->line:75] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"], res["code"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-02-28 20:59:57,178 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为负数，执行未通过
2020-02-28 20:59:57,178 - [test_wothdraw.py-->line:75] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-28 20:59:57,322 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额为空，执行未通过
2020-02-28 20:59:57,323 - [test_wothdraw.py-->line:75] - ERROR: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额为空' != '余额为空'
- 金额为空
? ^
+ 余额为空
? ^

2020-02-28 20:59:57,527 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额-3位小数，执行未通过
2020-02-28 20:59:57,527 - [test_wothdraw.py-->line:75] - ERROR: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额小数超过两位' != '余额小数超过两位'
- 金额小数超过两位
? ^
+ 余额小数超过两位
? ^

2020-02-28 20:59:57,703 - [test_wothdraw.py-->line:74] - ERROR: 用例：提现金额-大于50万，执行未通过
2020-02-28 20:59:57,703 - [test_wothdraw.py-->line:75] - ERROR: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +
Traceback (most recent call last):
  File "C:\project\py26_project\py26_api_test\testcases\test_wothdraw.py", line 64, in test_withdraw
    self.assertEqual(expected["msg"], res["msg"])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '金额必须大于0并且小于或者等于500000' != '余额必须大于0并且小于或者等于5000000'
- 金额必须大于0并且小于或者等于500000
? ^
+ 余额必须大于0并且小于或者等于5000000
? ^                    +

2020-02-28 20:59:57,900 - [test_wothdraw.py-->line:79] - INFO: 用例：提现金额-非数字，执行未通过
